services:
  n8n:
      image: docker.n8n.io/n8nio/n8n
      restart: unless-stopped
      env_file:
        - .env
      ports:
        - "5678:5678"
      volumes:
        - n8n_storage:/home/node/.n8n
        - ./custom-certs/rds-combined-ca-bundle.pem:/home/node/rds-combined-ca-bundle.pem:ro
volumes:
  n8n_storage:
